__include__: [
  '../dataset/chicken_detection.yml',
  '../../D-FINE/configs/runtime.yml',
  '../../D-FINE/configs/dfine/include/dataloader.yml',
  '../../D-FINE/configs/dfine/include/optimizer.yml',
  '../../D-FINE/configs/dfine/include/dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_l_chicken

HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0000125
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.00025
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epochs: 80
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 72
      collate_fn:
        stop_epoch: 72
        ema_restart_decay: 0.9999
        base_size_repeat: 4
