__include__: [
  '../dataset/chicken_detection.yml',
  '../../D-FINE/configs/runtime.yml',
  '../../D-FINE/configs/dfine/include/dataloader.yml',
  '../../D-FINE/configs/dfine/include/optimizer.yml',
  '../../D-FINE/configs/dfine/include/dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_s_chicken

DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B0'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

DFINETransformer:
  num_layers: 3
  eval_idx: -1

HybridEncoder:
  in_channels: [256, 512, 1024]
  hidden_dim: 256
  depth_mult: 0.34
  expansion: 0.5

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0001
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0001
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epochs: 132
train_dataloader:
  total_batch_size: 8
  dataset:
    transforms:
      policy:
        epoch: 120
  collate_fn:
    stop_epoch: 120
    ema_restart_decay: 0.9999
    base_size_repeat: 20

val_dataloader:
  total_batch_size: 16
